name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'z85base91/version.py'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'z85base91/version.py'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11" ]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig
          python -m pip install build wheel
      - name: Install repo
        run: |
          pip install -e .
      - name: Install test dependencies
        run: |
          pip install -r test/requirements.txt
      - name: Run unittests
        run: |
          pytest --cov=z85base91 --cov-report xml test
      - name: Upload coverage
        if: "${{ matrix.python-version == '3.11' }}"
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v2